Updated app.py and added model files
t add .
git commit -m "Enabled CORS for frontend access"
git push origin main
warning: in the working copy of 'app.py', LF will be replaced by CRLF
the next t
ime Git touches it
warning: in the working copy of 'requirements.txt', LF will be replaced
by CRLF
the next time Git touches it
[main 0b4dfc0] Enabled CORS for frontend access
 3 files changed, 85 insertions(+)
  create mode 100644 index.html
  To https://github.com/Zaheedali0007/resume-fraud-api.git
   ! [rejected]        main -> main (fetch first)
   error: failed to push some refs to
   'https://github.com/Zaheedali0007/resume-frau
   d-api.git'
   hint: Updates were rejected because the remote contains work that you
   do not
   Updated app.py and added model files

   # Conflicts:
   #       app.py
   #       requirements.txt

   # Please enter the commit message for your changes. Lines starting
   # with '#' will be ignored, and an empty message aborts the commit.
   #
   # interactive rebase in progress; onto 2a97361
   # Last command done (1 command done):
   #    pick 8e53cb7 Updated app.py and added model files
   # Next command to do (1 remaining command):
   #    pick 0b4dfc0 Enabled CORS for frontend access
   # You are currently rebasing branch 'main' on '2a97361'.
   #
   # Changes to be committed:
  #